statistics rudimentary

diff --git a/vocatrainer b/vocatrainer
--- a/vocatrainer
+++ b/vocatrainer
@@ -1,48 +1,57 @@
 #!/bin/bash
+set -e
+
 # Global and Quiz variables{{{
-COMMAND="cat"
-DEBUG=""
-INVERSE=""
-OUT="-"
-SEP="	"
-ERRORS=""
-TOTAL=0
-CORRECT=0
-FILESIN=0
-FILES=()
+DISPLAY_COMMAND="cat"
+F_DEBUG=""
+F_INV="0"
+INPUT_FILES=()
+INPUT_FILES_N=0
+INPUT_SEPARATOR="	"
+Q_CORRECT=0
+Q_TOTAL=0
+Q_ERROR_N=0
+Q_ERRORS=()
+LISTSTATS=0
+REDO_ERRORS=""
+SCORE_FILE="-"
 # Global variables}}}
 
 # Parsing command line options{{{
-while getopts "irhes:f:d1" opt;
+while getopts "irhes:f:d1l" opt;
 do
 	case $opt in
 		i)
-			INVERSE="1"
-			[ $DEBUG ] && echo "Inverse mode is on"
+			F_INV="1"
+			[ $F_DEBUG ] && echo "Inverse mode is on"
 			;;
 		r)
-			COMMAND="shuf"
-			[ $DEBUG ] && echo "Random mode is on"
+			DISPLAY_COMMAND="shuf"
+			[ $F_DEBUG ] && echo "Random mode is on"
 			;;
 		s)
-			SEP="$OPTARG"
-			[ $DEBUG ] && echo "Separator set"
+			INPUT_SEPARATOR="$OPTARG"
+			[ $F_DEBUG ] && echo "Separator set"
 			;;
 		f)
-			OUT="$OPTARG"
-			[ $DEBUG ] && echo "Output file set"
+			SCORE_FILE="$OPTARG"
+			[ $F_DEBUG ] && echo "Output file set"
 			;;
 		d)
-			DEBUG="1"
+			F_DEBUG="1"
 			echo "Debug flag on"
 			;;
 		e)
-			ERRORS="1"
-			[ $DEBUG ] && echo "Error reask set"
+			REDO_ERRORS="1"
+			[ $F_DEBUG ] && echo "Error reask set"
 			;;
 		1)
 			ONETIME="1"
-			[ $DEBUG ] && echo "One time only set"
+			[ $F_DEBUG ] && echo "One time only set"
+			;;
+		l)
+			LISTSTATS="1"
+			[ $F_DEBUG ] && echo "Listing statistics set"
 			;;
 		h)
 			echo "Usage:"
@@ -53,6 +62,7 @@ do
 			echo "	-f FILE Scores file, default: -"
 			echo "	-h      Show this help"
 			echo "	-i      Inverse the question and answer, default: false"
+			echo "  -l      List the statistics about files, default: false"
 			echo "	-r      Randomize the questions, default: false"
 			echo "	-s SEP  Custom separator, default: tab"
 			echo "  -1      One time only, don't write a stats file"
@@ -74,64 +84,96 @@ fi
 # Quizzing{{{
 while [ "$OPTIND" -le "$#" ]
 do
-	FILES[FILESIN]="${!OPTIND}"
-	TMPFILE=$(mktemp)
-	[ $DEBUG ] && echo "Temp file created: $TMPFILE"
-	$COMMAND "${FILES[FILESIN]}" >> "$TMPFILE"
-	[ $DEBUG ] && echo "File shuffled and written to temp"
-	exec 3<> "$TMPFILE"
-	[ $DEBUG ] && echo "Opening temp file descriptor"
-	while read -u 3 line
-	do
-		QUESTION=$(echo "$line" | cut -n -d "$SEP" -f 1)
-		[ $DEBUG ] && echo "Question extracted: $QUESTION"
-		ANSWER=$(echo "$line" | cut -n -d "$SEP" -f 2)
-		[ $DEBUG ] && echo "Answer extracted: $ANSWER"
-		if [ $INVERSE ]
-		then
-			TEMP="$QUESTION"
-			QUESTION="$ANSWER"
-			ANSWER="$TEMP"
-			[ $DEBUG ] && echo "Question and answer swapped"
-		fi
-		echo "$QUESTION"
-		echo -n "> "
-		read YOURANSWER
-		echo -n "The answer is: $ANSWER, "
-		if [ "$ANSWER" = "$YOURANSWER" ]
-		then
-			echo "This is correct!"
-			CORRECT=$((CORRECT + 1))
-		else
-		 	echo "Incorrect..."
-			if [ $ERRORS ]
+	INPUT_FILES[INPUT_FILES_N]="${!OPTIND}"
+	if [ "$LISTSTATS" = 0 ]
+	then
+		TMPFILE=$(mktemp)
+		[ $F_DEBUG ] && echo "Temp file created: $TMPFILE"
+		$DISPLAY_COMMAND "${INPUT_FILES[INPUT_FILES_N]}" >> "$TMPFILE"
+		[ $F_DEBUG ] && echo "File shuffled and written to temp"
+		exec 3<> "$TMPFILE"
+		[ $F_DEBUG ] && echo "Opening temp file descriptor"
+		while read -u 3 line
+		do
+			QUESTION=$(echo "$line" | cut -n -d "$INPUT_SEPARATOR" -f 1)
+			[ $F_DEBUG ] && echo "Question extracted: $QUESTION"
+			ANSWER=$(echo "$line" | cut -n -d "$INPUT_SEPARATOR" -f 2)
+			[ $F_DEBUG ] && echo "Answer extracted: $ANSWER"
+			if [ $F_INV = "1" ]
 			then
-				if [ $INVERSE ]
+				TEMP="$QUESTION"
+				QUESTION="$ANSWER"
+				ANSWER="$TEMP"
+				[ $F_DEBUG ] && echo "Question and answer swapped"
+			fi
+			echo "$QUESTION"
+			echo -n "> "
+			read YOURANSWER
+			echo -n "The answer is: $ANSWER, "
+			if [ "$ANSWER" = "$YOURANSWER" ]
+			then
+				echo "This is correct!"
+				Q_CORRECT=$((Q_CORRECT + 1))
+			else
+			 	echo "Incorrect..."
+				ERRORS[Q_ERRORS_N]="$QUESTION"
+				Q_ERRORS_N=$((Q_ERRORS_N + 1))
+				if [ $REDO_ERRORS ]
 				then
-					echo "$ANSWER	$QUESTION" >>$TMPFILE
-				else
-					echo "$QUESTION	$ANSWER" >>$TMPFILE
+					if [ $F_INV = "0" ]
+					then
+						echo "$ANSWER	$QUESTION" >>$TMPFILE
+					else
+						echo "$QUESTION	$ANSWER" >>$TMPFILE
+					fi
 				fi
 			fi
-		fi
-		TOTAL=$((TOTAL + 1))
-		[ $DEBUG ] && echo "Total questions asked: $TOTAL"
-	done
-	exec 3>&-
-	[ $DEBUG ] && echo "Closing temp file descriptor"
+			Q_TOTAL=$((Q_TOTAL + 1))
+			[ $F_DEBUG ] && echo "Total questions asked: $Q_TOTAL"
+		done
+		exec 3>&-
+		[ $F_DEBUG ] && echo "Closing temp file descriptor"
+	fi
 	OPTIND=$((OPTIND + 1))
-	FILESIN=$((FILESIN + 1))
+	INPUT_FILES_N=$((INPUT_FILES_N + 1))
 done
 # Quizzing}}}
 
-# Output scores and process statistics{{{
-OUTSTREAM=$(printf "_%s" "${FILES[@]}")
-OUTSTREAM=".${OUTSTREAM:1}.stats"
-exec 3<> "$OUTSTREAM"
-[ $DEBUG ] && echo "Filedescriptor for score opened: $OUTSTREAM"
+# Open and/or prepare stats file{{{
+if [ $SCOREFILE ]
+then
+	SCORE_STREAM="$SCOREFILE"
+	[ $F_DEBUG ] && echo "Manual score file opened: $SCORE_STREAM"
+else
+	SCORE_STREAM=$(printf "_%s" "${INPUT_FILES[@]}")
+	SCORE_STREAM="${SCORE_STREAM:1}.stats"
+	[ $F_DEBUG ] && echo "Score file opened: $SCORE_STREAM"
+fi
+if [ ! -s "$SCORE_STREAM" ]
+then
+	echo -e "Date\tTotal\tCorrect\tGrade\tInverse\tErrors" > $SCORE_STREAM
+	[ $F_DEBUG ] && echo "Header written"
+fi
+# Open and/or prepare stats file}}}
 
-echo "$OUTSTREAM"
-
-exec 3>&-
-[ $DEBUG ] && echo "Filedescriptor for score closed"
-# Output scores}}}
+if [ "$LISTSTATS" = "0" ]
+then
+	# Output scores and process statistics{{{
+	Q_GRADE=$(( ($Q_CORRECT*100)/10 ))
+	ERRORS=$(printf "_%s" "${ERRORS[@]}")
+	ERRORS=${ERRORS:1}
+	echo "Total: $Q_TOTAL"
+	echo "Correct: $Q_CORRECT"
+	echo "Grade: $Q_GRADE/100"
+	echo "Errors: $ERRORS"
+	
+	echo -en "$(date +%Y-%m-%d\ %H:%m:%S)\t" >> $SCORE_STREAM
+	[ $F_DEBUG ] && echo "Date written"
+	echo -e "$Q_TOTAL\t$Q_CORRECT\t$Q_GRADE\t$F_INV\t$ERRORS" >> $SCORE_STREAM
+	[ $F_DEBUG ] && echo "Data written"
+	# Output scores}}}
+else
+	# List statistics{{{
+	awk '{sum+=$3;print}END{print "Avg: ",sum/NR}' "$SCORE_STREAM" | column -t
+	# List statistics}}}
+fi
